// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared;

#nullable disable

namespace BookStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241107214747_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb6cbf99-ea1f-40dc-bb4a-80bbc595d234"),
                            Author = "Author 1",
                            Category = "Drama",
                            CoverImageUrl = "/images/good-paper-wattpad-book.jpg",
                            CreatedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7108),
                            IsFeatured = true,
                            ModifiedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7127),
                            Price = 100.98999999999999,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = new Guid("a885076f-6d95-4b5a-841f-3afdbd082702"),
                            Author = "Author 2",
                            Category = "Fiction",
                            CoverImageUrl = "/images/poster-template-new-scientists.jpg",
                            CreatedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7156),
                            IsFeatured = true,
                            ModifiedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7157),
                            Price = 200.0,
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = new Guid("bde62685-6c17-43d1-bcf1-1af39b2d58fc"),
                            Author = "Author 3",
                            Category = "Tragedy",
                            CoverImageUrl = "/images/pumpkin-drink-poster.jpg",
                            CreatedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7163),
                            IsFeatured = true,
                            ModifiedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7163),
                            Price = 14.0,
                            Title = "Book 3"
                        },
                        new
                        {
                            Id = new Guid("a24a6355-8f92-4857-9b69-211319dbcb1e"),
                            Author = "Author 4",
                            Category = "Fiction",
                            CoverImageUrl = "/images/bookcover1.jpg",
                            CreatedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7168),
                            IsFeatured = true,
                            ModifiedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7169),
                            Price = 5.0,
                            Title = "Book 4"
                        },
                        new
                        {
                            Id = new Guid("b12a2281-9db1-4d3d-9dc4-de3881ffdf15"),
                            Author = "Author 5",
                            Category = "Fiction",
                            CoverImageUrl = "/images/online-education-poster-template.jpg",
                            CreatedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7192),
                            IsFeatured = true,
                            ModifiedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7192),
                            Price = 1409.0,
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = new Guid("ee95a674-0c4d-4d3b-b676-4e6e25c03732"),
                            Author = "Author 6",
                            Category = "Fiction",
                            CoverImageUrl = "/images/bookcover1.jpg",
                            CreatedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7197),
                            IsFeatured = true,
                            ModifiedOn = new DateTime(2024, 11, 7, 22, 47, 46, 118, DateTimeKind.Local).AddTicks(7198),
                            Price = 5.0,
                            Title = "Book 6"
                        });
                });

            modelBuilder.Entity("BookStore.Models.ContactUs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });
#pragma warning restore 612, 618
        }
    }
}
